
**
** successfully loaded python MPI module (mpi4py)
**
Traceback (most recent call last):
  File "model_builder.py", line 169, in <module>
    Traceback (most recent call last):
  File "model_builder.py", line 169, in <module>
    main()
  File "model_builder.py", line 163, in main
    i_w = float(sys.argv[2])
IndexError: list index out of range
Traceback (most recent call last):
  File "model_builder.py", line 169, in <module>
    main()
  File "model_builder.py", line 163, in main
    i_w = float(sys.argv[2])
IndexError: list index out of range
main()
  File "model_builder.py", line 163, in main
    i_w = float(sys.argv[2])
IndexError: list index out of range
Traceback (most recent call last):
  File "model_builder.py", line 169, in <module>
    main()
  File "model_builder.py", line 163, in main
    i_w = float(sys.argv[2])
IndexError: list index out of range
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[11317,1],0]
  Exit code:    1
--------------------------------------------------------------------------
